name = "Quicker Pixels"
license = "Apache-2.0"
licenselink = "https://github.com/toughpixels/quick-pixels/blob/main/LICENSE"
description = ""
homepage = ""
tags = ["blog" ]
features = ["blog"]
min_version = "0.0.1"

[author]
  name = ""
  homepage = ""
