languageCode = "en-us"
theme = ["quicker-pixels"]
title = "Grow a Plant!"
baseURL = "https://growaplant.netlify.app"

# If you don't want english/spanish support, comment the below...

defaultContentLanguage = 'en'
[languages]
[languages.en]
    languageName = "English"
    weight = 1
[languages.es]
   languageName = 'español'
   weight = 2

# If you want to remove these taxonomies, uncomment below (and/or add new ones)

[taxonomies]
  category = 'categories'
  tag = 'tags'


[params]
  minimumWordsNeededToShowScrollTopLink = 100

  themeVars = "--background_color: #FFFCF4;\n--background_color_off: #EFFEFF;\n--action_color: #D500A2;\n--accent_color: #16009F;\n--text_color: #202020;\n--leadText_size: 2rem;\n--leadText_align: center;\n--font_family: ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;\n--alt_background_color: var(--accent_color);\n--default_font_size: 1.5rem;\n--default_line_height:1.6; \n--header_font_family: var(--font_family);\n--h1_size: 4rem;\n--h2_size: 3.5rem;\n--h3_size: 3rem;\n--h4_size: 2.5rem;\n--h5_size: 2rem;\n--h6_size: 1.5rem;\n--header_size_mobile_reduction: 1.5;\n--h1_weight: 400;\n--h2_weight: 700;\n--h3_weight: 400;\n--h4_weight: 700;\n--h5_weight: 400;\n--h6_weight: 700;\n--h1_line_height: 1.1;\n--h2_line_height: 1.2;\n--h3_line_height: 1.3;\n--h4_line_height: 1.4;\n--h5_line_height: 1.5;\n--h6_line_height: 1.6;"

  ## you may want to override these options per page
  showFooter = true
  showBreadcrumbs = true

  showDescription = true
  showMeta = true
  showMetaWords = true
  showMetaDate = true
  
  showSiblingNavOfChildPages = true
  addExternalLinkJavascript = true

[markup]

[markup.goldmark]

[markup.goldmark.renderer]
unsafe = true